// Generated by gencpp from file fourth_proj/addsrvRequest.msg
// DO NOT EDIT!


#ifndef FOURTH_PROJ_MESSAGE_ADDSRVREQUEST_H
#define FOURTH_PROJ_MESSAGE_ADDSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fourth_proj
{
template <class ContainerAllocator>
struct addsrvRequest_
{
  typedef addsrvRequest_<ContainerAllocator> Type;

  addsrvRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  addsrvRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::fourth_proj::addsrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fourth_proj::addsrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addsrvRequest_

typedef ::fourth_proj::addsrvRequest_<std::allocator<void> > addsrvRequest;

typedef boost::shared_ptr< ::fourth_proj::addsrvRequest > addsrvRequestPtr;
typedef boost::shared_ptr< ::fourth_proj::addsrvRequest const> addsrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fourth_proj::addsrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fourth_proj::addsrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fourth_proj

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fourth_proj': ['/home/workshop/new_ws/src/fourth_proj/msg', '/home/workshop/new_ws/devel/share/fourth_proj/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::addsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::addsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::addsrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f4f9f1b571de73ae8592a1438fd23f3";
  }

  static const char* value(const ::fourth_proj::addsrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f4f9f1b571de73aULL;
  static const uint64_t static_value2 = 0xe8592a1438fd23f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fourth_proj/addsrvRequest";
  }

  static const char* value(const ::fourth_proj::addsrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n\
float64 b\n\
";
  }

  static const char* value(const ::fourth_proj::addsrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addsrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fourth_proj::addsrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fourth_proj::addsrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOURTH_PROJ_MESSAGE_ADDSRVREQUEST_H
