// Generated by gencpp from file fourth_proj/addsrv.msg
// DO NOT EDIT!


#ifndef FOURTH_PROJ_MESSAGE_ADDSRV_H
#define FOURTH_PROJ_MESSAGE_ADDSRV_H

#include <ros/service_traits.h>


#include <fourth_proj/addsrvRequest.h>
#include <fourth_proj/addsrvResponse.h>


namespace fourth_proj
{

struct addsrv
{

typedef addsrvRequest Request;
typedef addsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addsrv
} // namespace fourth_proj


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fourth_proj::addsrv > {
  static const char* value()
  {
    return "6e7c4f317ab6ba70dfa7c335adfdc1c7";
  }

  static const char* value(const ::fourth_proj::addsrv&) { return value(); }
};

template<>
struct DataType< ::fourth_proj::addsrv > {
  static const char* value()
  {
    return "fourth_proj/addsrv";
  }

  static const char* value(const ::fourth_proj::addsrv&) { return value(); }
};


// service_traits::MD5Sum< ::fourth_proj::addsrvRequest> should match 
// service_traits::MD5Sum< ::fourth_proj::addsrv > 
template<>
struct MD5Sum< ::fourth_proj::addsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fourth_proj::addsrv >::value();
  }
  static const char* value(const ::fourth_proj::addsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fourth_proj::addsrvRequest> should match 
// service_traits::DataType< ::fourth_proj::addsrv > 
template<>
struct DataType< ::fourth_proj::addsrvRequest>
{
  static const char* value()
  {
    return DataType< ::fourth_proj::addsrv >::value();
  }
  static const char* value(const ::fourth_proj::addsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fourth_proj::addsrvResponse> should match 
// service_traits::MD5Sum< ::fourth_proj::addsrv > 
template<>
struct MD5Sum< ::fourth_proj::addsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fourth_proj::addsrv >::value();
  }
  static const char* value(const ::fourth_proj::addsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fourth_proj::addsrvResponse> should match 
// service_traits::DataType< ::fourth_proj::addsrv > 
template<>
struct DataType< ::fourth_proj::addsrvResponse>
{
  static const char* value()
  {
    return DataType< ::fourth_proj::addsrv >::value();
  }
  static const char* value(const ::fourth_proj::addsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOURTH_PROJ_MESSAGE_ADDSRV_H
