// Generated by gencpp from file fourth_proj/cmdmsg.msg
// DO NOT EDIT!


#ifndef FOURTH_PROJ_MESSAGE_CMDMSG_H
#define FOURTH_PROJ_MESSAGE_CMDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fourth_proj
{
template <class ContainerAllocator>
struct cmdmsg_
{
  typedef cmdmsg_<ContainerAllocator> Type;

  cmdmsg_()
    : header()
    , vl(0.0)
    , vr(0.0)  {
    }
  cmdmsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vl(0.0)
    , vr(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _vl_type;
  _vl_type vl;

   typedef double _vr_type;
  _vr_type vr;





  typedef boost::shared_ptr< ::fourth_proj::cmdmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fourth_proj::cmdmsg_<ContainerAllocator> const> ConstPtr;

}; // struct cmdmsg_

typedef ::fourth_proj::cmdmsg_<std::allocator<void> > cmdmsg;

typedef boost::shared_ptr< ::fourth_proj::cmdmsg > cmdmsgPtr;
typedef boost::shared_ptr< ::fourth_proj::cmdmsg const> cmdmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fourth_proj::cmdmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fourth_proj::cmdmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fourth_proj

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'fourth_proj': ['/home/workshop/new_ws/src/fourth_proj/msg', '/home/workshop/new_ws/devel/share/fourth_proj/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::cmdmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::cmdmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::cmdmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::cmdmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::cmdmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::cmdmsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fourth_proj::cmdmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f54d6e9a6e07cae4bfef7c0f8143142";
  }

  static const char* value(const ::fourth_proj::cmdmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f54d6e9a6e07caeULL;
  static const uint64_t static_value2 = 0x4bfef7c0f8143142ULL;
};

template<class ContainerAllocator>
struct DataType< ::fourth_proj::cmdmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fourth_proj/cmdmsg";
  }

  static const char* value(const ::fourth_proj::cmdmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fourth_proj::cmdmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 vl\n\
float64 vr\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::fourth_proj::cmdmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fourth_proj::cmdmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vl);
      stream.next(m.vr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmdmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fourth_proj::cmdmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fourth_proj::cmdmsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vl: ";
    Printer<double>::stream(s, indent + "  ", v.vl);
    s << indent << "vr: ";
    Printer<double>::stream(s, indent + "  ", v.vr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOURTH_PROJ_MESSAGE_CMDMSG_H
