// Generated by gencpp from file fourth_proj/delayactionResult.msg
// DO NOT EDIT!


#ifndef FOURTH_PROJ_MESSAGE_DELAYACTIONRESULT_H
#define FOURTH_PROJ_MESSAGE_DELAYACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fourth_proj
{
template <class ContainerAllocator>
struct delayactionResult_
{
  typedef delayactionResult_<ContainerAllocator> Type;

  delayactionResult_()
    : b(0)  {
    }
  delayactionResult_(const ContainerAllocator& _alloc)
    : b(0)  {
  (void)_alloc;
    }



   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::fourth_proj::delayactionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fourth_proj::delayactionResult_<ContainerAllocator> const> ConstPtr;

}; // struct delayactionResult_

typedef ::fourth_proj::delayactionResult_<std::allocator<void> > delayactionResult;

typedef boost::shared_ptr< ::fourth_proj::delayactionResult > delayactionResultPtr;
typedef boost::shared_ptr< ::fourth_proj::delayactionResult const> delayactionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fourth_proj::delayactionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fourth_proj::delayactionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fourth_proj

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fourth_proj': ['/home/workshop/new_ws/src/fourth_proj/msg', '/home/workshop/new_ws/devel/share/fourth_proj/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::delayactionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::delayactionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::delayactionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::delayactionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::delayactionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::delayactionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fourth_proj::delayactionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5a3c6284d5ab11e232db053f443f102";
  }

  static const char* value(const ::fourth_proj::delayactionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5a3c6284d5ab11eULL;
  static const uint64_t static_value2 = 0x232db053f443f102ULL;
};

template<class ContainerAllocator>
struct DataType< ::fourth_proj::delayactionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fourth_proj/delayactionResult";
  }

  static const char* value(const ::fourth_proj::delayactionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fourth_proj::delayactionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Part2: Result defination\n\
int64 b\n\
";
  }

  static const char* value(const ::fourth_proj::delayactionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fourth_proj::delayactionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct delayactionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fourth_proj::delayactionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fourth_proj::delayactionResult_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOURTH_PROJ_MESSAGE_DELAYACTIONRESULT_H
