// Generated by gencpp from file fourth_proj/sensmsg.msg
// DO NOT EDIT!


#ifndef FOURTH_PROJ_MESSAGE_SENSMSG_H
#define FOURTH_PROJ_MESSAGE_SENSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fourth_proj
{
template <class ContainerAllocator>
struct sensmsg_
{
  typedef sensmsg_<ContainerAllocator> Type;

  sensmsg_()
    : header()
    , front(0.0)
    , left(0.0)
    , right(0.0)  {
    }
  sensmsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , front(0.0)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _front_type;
  _front_type front;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::fourth_proj::sensmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fourth_proj::sensmsg_<ContainerAllocator> const> ConstPtr;

}; // struct sensmsg_

typedef ::fourth_proj::sensmsg_<std::allocator<void> > sensmsg;

typedef boost::shared_ptr< ::fourth_proj::sensmsg > sensmsgPtr;
typedef boost::shared_ptr< ::fourth_proj::sensmsg const> sensmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fourth_proj::sensmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fourth_proj::sensmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fourth_proj

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'fourth_proj': ['/home/workshop/new_ws/src/fourth_proj/msg', '/home/workshop/new_ws/devel/share/fourth_proj/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::sensmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fourth_proj::sensmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::sensmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fourth_proj::sensmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::sensmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fourth_proj::sensmsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fourth_proj::sensmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21187edbb23f50ee9495d83e3795ee9f";
  }

  static const char* value(const ::fourth_proj::sensmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21187edbb23f50eeULL;
  static const uint64_t static_value2 = 0x9495d83e3795ee9fULL;
};

template<class ContainerAllocator>
struct DataType< ::fourth_proj::sensmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fourth_proj/sensmsg";
  }

  static const char* value(const ::fourth_proj::sensmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fourth_proj::sensmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 front\n\
float64 left\n\
float64 right\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::fourth_proj::sensmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fourth_proj::sensmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.front);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fourth_proj::sensmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fourth_proj::sensmsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "front: ";
    Printer<double>::stream(s, indent + "  ", v.front);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOURTH_PROJ_MESSAGE_SENSMSG_H
