(cl:defpackage fourth_proj-msg
  (:use )
  (:export
   "<CMDMSG>"
   "CMDMSG"
   "<DELAYACTIONACTION>"
   "DELAYACTIONACTION"
   "<DELAYACTIONACTIONFEEDBACK>"
   "DELAYACTIONACTIONFEEDBACK"
   "<DELAYACTIONACTIONGOAL>"
   "DELAYACTIONACTIONGOAL"
   "<DELAYACTIONACTIONRESULT>"
   "DELAYACTIONACTIONRESULT"
   "<DELAYACTIONFEEDBACK>"
   "DELAYACTIONFEEDBACK"
   "<DELAYACTIONGOAL>"
   "DELAYACTIONGOAL"
   "<DELAYACTIONRESULT>"
   "DELAYACTIONRESULT"
   "<SENSMSG>"
   "SENSMSG"
  ))

