; Auto-generated. Do not edit!


(cl:in-package fourth_proj-msg)


;//! \htmlinclude delayactionFeedback.msg.html

(cl:defclass <delayactionFeedback> (roslisp-msg-protocol:ros-message)
  ((c
    :reader c
    :initarg :c
    :type cl:integer
    :initform 0))
)

(cl:defclass delayactionFeedback (<delayactionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <delayactionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'delayactionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fourth_proj-msg:<delayactionFeedback> is deprecated: use fourth_proj-msg:delayactionFeedback instead.")))

(cl:ensure-generic-function 'c-val :lambda-list '(m))
(cl:defmethod c-val ((m <delayactionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fourth_proj-msg:c-val is deprecated.  Use fourth_proj-msg:c instead.")
  (c m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <delayactionFeedback>) ostream)
  "Serializes a message object of type '<delayactionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'c)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <delayactionFeedback>) istream)
  "Deserializes a message object of type '<delayactionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'c) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<delayactionFeedback>)))
  "Returns string type for a message object of type '<delayactionFeedback>"
  "fourth_proj/delayactionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'delayactionFeedback)))
  "Returns string type for a message object of type 'delayactionFeedback"
  "fourth_proj/delayactionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<delayactionFeedback>)))
  "Returns md5sum for a message object of type '<delayactionFeedback>"
  "90f689545dad66929d15414b42274955")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'delayactionFeedback)))
  "Returns md5sum for a message object of type 'delayactionFeedback"
  "90f689545dad66929d15414b42274955")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<delayactionFeedback>)))
  "Returns full string definition for message of type '<delayactionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part3: Feedback defination~%int64 c~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'delayactionFeedback)))
  "Returns full string definition for message of type 'delayactionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part3: Feedback defination~%int64 c~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <delayactionFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <delayactionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'delayactionFeedback
    (cl:cons ':c (c msg))
))
