; Auto-generated. Do not edit!


(cl:in-package fourth_proj-msg)


;//! \htmlinclude delayactionGoal.msg.html

(cl:defclass <delayactionGoal> (roslisp-msg-protocol:ros-message)
  ((a
    :reader a
    :initarg :a
    :type cl:integer
    :initform 0))
)

(cl:defclass delayactionGoal (<delayactionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <delayactionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'delayactionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fourth_proj-msg:<delayactionGoal> is deprecated: use fourth_proj-msg:delayactionGoal instead.")))

(cl:ensure-generic-function 'a-val :lambda-list '(m))
(cl:defmethod a-val ((m <delayactionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fourth_proj-msg:a-val is deprecated.  Use fourth_proj-msg:a instead.")
  (a m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <delayactionGoal>) ostream)
  "Serializes a message object of type '<delayactionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'a)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <delayactionGoal>) istream)
  "Deserializes a message object of type '<delayactionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'a) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<delayactionGoal>)))
  "Returns string type for a message object of type '<delayactionGoal>"
  "fourth_proj/delayactionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'delayactionGoal)))
  "Returns string type for a message object of type 'delayactionGoal"
  "fourth_proj/delayactionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<delayactionGoal>)))
  "Returns md5sum for a message object of type '<delayactionGoal>"
  "019706110004b728d56d8baaa8e32797")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'delayactionGoal)))
  "Returns md5sum for a message object of type 'delayactionGoal"
  "019706110004b728d56d8baaa8e32797")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<delayactionGoal>)))
  "Returns full string definition for message of type '<delayactionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part1: Goal defination~%int64 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'delayactionGoal)))
  "Returns full string definition for message of type 'delayactionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part1: Goal defination~%int64 a~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <delayactionGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <delayactionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'delayactionGoal
    (cl:cons ':a (a msg))
))
