; Auto-generated. Do not edit!


(cl:in-package fourth_proj-msg)


;//! \htmlinclude delayactionResult.msg.html

(cl:defclass <delayactionResult> (roslisp-msg-protocol:ros-message)
  ((b
    :reader b
    :initarg :b
    :type cl:integer
    :initform 0))
)

(cl:defclass delayactionResult (<delayactionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <delayactionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'delayactionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fourth_proj-msg:<delayactionResult> is deprecated: use fourth_proj-msg:delayactionResult instead.")))

(cl:ensure-generic-function 'b-val :lambda-list '(m))
(cl:defmethod b-val ((m <delayactionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fourth_proj-msg:b-val is deprecated.  Use fourth_proj-msg:b instead.")
  (b m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <delayactionResult>) ostream)
  "Serializes a message object of type '<delayactionResult>"
  (cl:let* ((signed (cl:slot-value msg 'b)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <delayactionResult>) istream)
  "Deserializes a message object of type '<delayactionResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'b) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<delayactionResult>)))
  "Returns string type for a message object of type '<delayactionResult>"
  "fourth_proj/delayactionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'delayactionResult)))
  "Returns string type for a message object of type 'delayactionResult"
  "fourth_proj/delayactionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<delayactionResult>)))
  "Returns md5sum for a message object of type '<delayactionResult>"
  "b5a3c6284d5ab11e232db053f443f102")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'delayactionResult)))
  "Returns md5sum for a message object of type 'delayactionResult"
  "b5a3c6284d5ab11e232db053f443f102")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<delayactionResult>)))
  "Returns full string definition for message of type '<delayactionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part2: Result defination~%int64 b~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'delayactionResult)))
  "Returns full string definition for message of type 'delayactionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Part2: Result defination~%int64 b~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <delayactionResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <delayactionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'delayactionResult
    (cl:cons ':b (b msg))
))
